name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: iPhone 11 Test
      run: xcodebuild test -scheme WordCamp -project WordCamp.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'
    - name: Swift Doc
      uses: SwiftDocOrg/swift-doc@0.0.1      
