name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    # run: ls /Applications | grep Xcode
    - name: Force xcode 11
    run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: iPhone 11 Test
    run: xcodebuild test -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'
    - name: Swift Doc
      uses: SwiftDocOrg/swift-doc@0.0.1      
